apiVersion: v1
kind: Service
metadata:
  name: careeros-api
  namespace: careeros
  labels:
    app: careeros-api
spec:
  selector:
    app: careeros-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
