apiVersion: apps/v1
kind: Deployment
metadata:
  name: careeros-redis
  namespace: careeros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: careeros-redis
  template:
    metadata:
      labels:
        app: careeros-redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          command: ["redis-server", "--appendonly", "yes"]
