apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: careeros
stringData:
  POSTGRES_PASSWORD: change_me_in_production
  REDIS_PASSWORD: change_me_in_production
  SECRET_KEY: change_me_in_production
